/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/super-tabs.module';
import * as i2 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as i3 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as i4 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as i5 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as i6 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as i7 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as i8 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as i9 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as i10 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as i11 from '@angular/common';
import * as i12 from '@angular/forms';
import * as i13 from 'ionic-angular/module';
export const SuperTabsModuleNgFactory:i0.NgModuleFactory<i1.SuperTabsModule> = i0.ɵcmf(i1.SuperTabsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ActionSheetCmpNgFactory,i3.AlertCmpNgFactory,i4.IonicAppNgFactory,
              i5.LoadingCmpNgFactory,i6.ModalCmpNgFactory,i7.PickerCmpNgFactory,i8.PopoverCmpNgFactory,
              i9.SelectPopoverNgFactory,i10.ToastCmpNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i11.NgLocalization,i11.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i12.ɵi,i12.ɵi,([] as any[])),i0.ɵmpd(4608,i12.FormBuilder,
          i12.FormBuilder,([] as any[])),i0.ɵmpd(512,i11.CommonModule,i11.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i12.ɵba,i12.ɵba,([] as any[])),i0.ɵmpd(512,i12.FormsModule,
          i12.FormsModule,([] as any[])),i0.ɵmpd(512,i12.ReactiveFormsModule,i12.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i13.IonicModule,i13.IonicModule,([] as any[])),
          i0.ɵmpd(512,i1.SuperTabsModule,i1.SuperTabsModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RldnJlcS9yZXBvcy9pb25pYzItc3VwZXItdGFicy9zcmMvc3VwZXItdGFicy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGV2cmVxL3JlcG9zL2lvbmljMi1zdXBlci10YWJzL3NyYy9zdXBlci10YWJzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
