/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/components/super-tabs-container';
import * as i2 from 'ionic-angular/platform/platform';
const styles_SuperTabsContainer:any[] = ([] as any[]);
export const RenderType_SuperTabsContainer:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SuperTabsContainer,data:{}});
export function View_SuperTabsContainer_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{container:0}),(_l()(),i0.ɵeld(0,[[1,0],['container',
      1]],(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_SuperTabsContainer_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'super-tabs-container',
      ([] as any[]),(null as any),(null as any),(null as any),View_SuperTabsContainer_0,
      RenderType_SuperTabsContainer)),i0.ɵdid(4374528,(null as any),0,i1.SuperTabsContainer,
      [i0.ElementRef,i0.Renderer2,i2.Platform,i0.NgZone],(null as any),(null as any))],
      (null as any),(null as any));
}
export const SuperTabsContainerNgFactory:i0.ComponentFactory<i1.SuperTabsContainer> = i0.ɵccf('super-tabs-container',
    i1.SuperTabsContainer,View_SuperTabsContainer_Host_0,{config:'config',tabsCount:'tabsCount',
        selectedTabIndex:'selectedTabIndex'},{tabSelect:'tabSelect',onDrag:'onDrag'},
    ['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RldnJlcS9yZXBvcy9pb25pYzItc3VwZXItdGFicy9zcmMvY29tcG9uZW50cy9zdXBlci10YWJzLWNvbnRhaW5lci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9kZXZyZXEvcmVwb3MvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFicy1jb250YWluZXIudHMiLCJuZzovLy9Vc2Vycy9kZXZyZXEvcmVwb3MvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFicy1jb250YWluZXIudHMuU3VwZXJUYWJzQ29udGFpbmVyLmh0bWwiLCJuZzovLy9Vc2Vycy9kZXZyZXEvcmVwb3MvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFicy1jb250YWluZXIudHMuU3VwZXJUYWJzQ29udGFpbmVyX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAjY29udGFpbmVyPjxuZy1jb250ZW50PjwvbmctY29udGVudD48L2Rpdj4iLCI8c3VwZXItdGFicy1jb250YWluZXI+PC9zdXBlci10YWJzLWNvbnRhaW5lcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7dURDQUE7TUFBQTtNQUFBLHFDQUFnQjs7O29CQ0FoQjtNQUFBO21DQUFBLFVBQUE7TUFBQTs7Ozs7OyJ9
